include(InstallRequiredSystemLibraries)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_VERSION_MAJOR "${ca_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${ca_VERSION_MINOR}")

include(CPack)

